## Fixed-Type Arrays 

In [200]:
import array
L = list(range(10))
# integer array
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [201]:
A + 3

TypeError: can only append array (not "int") to array

In [202]:
array.array('f', L)

array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])

## Numpy Arrays

In [203]:
import numpy as np

B = np.array([1, 4, 2, 5, 3])
B

array([1, 4, 2, 5, 3])

In [204]:
B + 3

array([4, 7, 5, 8, 6])

In [205]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [206]:
# type 지정
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [207]:
# 다차원 array
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Generator

In [208]:
# 모든 요소가 0인 array
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [209]:
# 모든 요소가 1인 3x5 array
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [210]:
# 모든 요소가 3.14인 3x5 array
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [211]:
np.arange(0, 20, 2)  # np.array(range(0, 20, 2))

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [212]:
# 균등 분포
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [213]:
# random
np.random.random((3, 3))

array([[0.44994999, 0.61306346, 0.90234858],
       [0.09928035, 0.96980907, 0.65314004],
       [0.17090959, 0.35815217, 0.75068614]])

In [214]:
# normally distributed random values
np.random.normal(0, 1, (3, 3))

array([[-1.60540226,  0.98947618,  0.11081461],
       [-0.38093141,  0.11495917,  0.34531264],
       [-1.73495876,  1.65835111,  2.29977152]])

In [215]:
np.random.randint(0, 10, (3, 3))

array([[5, 5, 0],
       [1, 5, 9],
       [3, 0, 5]])

In [216]:
# 대각 행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [217]:
np.empty(3)

array([1., 1., 1.])

## Data Types

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

## Attributes

In [218]:
# 3차원 array 생성
import numpy as np
np.random.seed(0)  
x3 = np.random.randint(10, size=(3, 4, 5))  
x3

array([[[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1],
        [6, 7, 7, 8, 1]],

       [[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1]],

       [[9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6],
        [8, 4, 1, 4, 9]]])

In [219]:
from IPython.core.interactiveshell import InteractiveShell
# print()로 출력하지 않아도 모든 값이 출력되게 만들어줌.
InteractiveShell.ast_node_interactivity = "all"

In [220]:
x3.ndim
x3.shape
x3.size

3

(3, 4, 5)

60

In [221]:
# dtype => DataType 
# 말그대로 데이터 타입을 확인 혹은 생성시 지정할때 사용한다.
x3.dtype

dtype('int32')

In [222]:
# 요소 크기, 전체 크기
x3.itemsize # 요소 1개의 크기
# 요소의크기 * 요소 개수
# itemsize x size 
x3.nbytes 

4

240

## Indexing

#### - access single

In [223]:
x3

array([[[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1],
        [6, 7, 7, 8, 1]],

       [[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1]],

       [[9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6],
        [8, 4, 1, 4, 9]]])

In [224]:
x3[0]

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1]])

In [225]:
x3[0][1]

array([9, 3, 5, 2, 4])

In [226]:
x3[0][1][2]

5

In [227]:
x3[-1]

array([[9, 9, 0, 4, 7],
       [3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6],
       [8, 4, 1, 4, 9]])

In [228]:
x3[0, 1, 2] = 100
x3

array([[[  5,   0,   3,   3,   7],
        [  9,   3, 100,   2,   4],
        [  7,   6,   8,   8,   1],
        [  6,   7,   7,   8,   1]],

       [[  5,   9,   8,   9,   4],
        [  3,   0,   3,   5,   0],
        [  2,   3,   8,   1,   3],
        [  3,   3,   7,   0,   1]],

       [[  9,   9,   0,   4,   7],
        [  3,   2,   7,   2,   0],
        [  0,   4,   5,   5,   6],
        [  8,   4,   1,   4,   9]]])

In [229]:
# auto type casting
x3[0, 1, 2] = 100.34
x3

array([[[  5,   0,   3,   3,   7],
        [  9,   3, 100,   2,   4],
        [  7,   6,   8,   8,   1],
        [  6,   7,   7,   8,   1]],

       [[  5,   9,   8,   9,   4],
        [  3,   0,   3,   5,   0],
        [  2,   3,   8,   1,   3],
        [  3,   3,   7,   0,   1]],

       [[  9,   9,   0,   4,   7],
        [  3,   2,   7,   2,   0],
        [  0,   4,   5,   5,   6],
        [  8,   4,   1,   4,   9]]])

#### - Access Subarrays

``` python
x[start:stop:step]
x[start::step]
```

In [230]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [231]:
x[:5]  

array([0, 1, 2, 3, 4])

In [232]:
x[5:]  

array([5, 6, 7, 8, 9])

In [233]:
x[4:7]  

array([4, 5, 6])

In [234]:
x[::2]  
x[1::2]
x[3::-1]
x[::-1]

array([0, 2, 4, 6, 8])

array([1, 3, 5, 7, 9])

array([3, 2, 1, 0])

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [235]:
x3[:1, :2, :1]

array([[[5],
        [9]]])

In [236]:
x3[::-1, ::-1, ::-1]

array([[[  9,   4,   1,   4,   8],
        [  6,   5,   5,   4,   0],
        [  0,   2,   7,   2,   3],
        [  7,   4,   0,   9,   9]],

       [[  1,   0,   7,   3,   3],
        [  3,   1,   8,   3,   2],
        [  0,   5,   3,   0,   3],
        [  4,   9,   8,   9,   5]],

       [[  1,   8,   7,   7,   6],
        [  1,   8,   8,   6,   7],
        [  4,   2, 100,   3,   9],
        [  7,   3,   3,   0,   5]]])

In [237]:
x3[:, 0, 0]

array([5, 5, 9])

In [238]:
x4 = np.arange(1,61).reshape(3,4,5)
x4

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [239]:
print(x4[::-1],'\n')
print(x4[::-1,::-1])
print(x4[::-1,::-1,::-1])

[[[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]] 

[[[56 57 58 59 60]
  [51 52 53 54 55]
  [46 47 48 49 50]
  [41 42 43 44 45]]

 [[36 37 38 39 40]
  [31 32 33 34 35]
  [26 27 28 29 30]
  [21 22 23 24 25]]

 [[16 17 18 19 20]
  [11 12 13 14 15]
  [ 6  7  8  9 10]
  [ 1  2  3  4  5]]]
[[[60 59 58 57 56]
  [55 54 53 52 51]
  [50 49 48 47 46]
  [45 44 43 42 41]]

 [[40 39 38 37 36]
  [35 34 33 32 31]
  [30 29 28 27 26]
  [25 24 23 22 21]]

 [[20 19 18 17 16]
  [15 14 13 12 11]
  [10  9  8  7  6]
  [ 5  4  3  2  1]]]


### Subarrays 의 반환값은 ``view``


In [240]:
sub = x3[0, :, :]
sub

array([[  5,   0,   3,   3,   7],
       [  9,   3, 100,   2,   4],
       [  7,   6,   8,   8,   1],
       [  6,   7,   7,   8,   1]])

In [241]:
sub[0, 0] = 300
sub

array([[300,   0,   3,   3,   7],
       [  9,   3, 100,   2,   4],
       [  7,   6,   8,   8,   1],
       [  6,   7,   7,   8,   1]])

In [242]:
# x3도 변경됨
x3

array([[[300,   0,   3,   3,   7],
        [  9,   3, 100,   2,   4],
        [  7,   6,   8,   8,   1],
        [  6,   7,   7,   8,   1]],

       [[  5,   9,   8,   9,   4],
        [  3,   0,   3,   5,   0],
        [  2,   3,   8,   1,   3],
        [  3,   3,   7,   0,   1]],

       [[  9,   9,   0,   4,   7],
        [  3,   2,   7,   2,   0],
        [  0,   4,   5,   5,   6],
        [  8,   4,   1,   4,   9]]])

## array copy

In [243]:
sub = x3[0, :, :].copy()
sub

array([[300,   0,   3,   3,   7],
       [  9,   3, 100,   2,   4],
       [  7,   6,   8,   8,   1],
       [  6,   7,   7,   8,   1]])

In [244]:
sub[0, 0] = 900
sub

array([[900,   0,   3,   3,   7],
       [  9,   3, 100,   2,   4],
       [  7,   6,   8,   8,   1],
       [  6,   7,   7,   8,   1]])

In [245]:
# x3는 그대로
x3

array([[[300,   0,   3,   3,   7],
        [  9,   3, 100,   2,   4],
        [  7,   6,   8,   8,   1],
        [  6,   7,   7,   8,   1]],

       [[  5,   9,   8,   9,   4],
        [  3,   0,   3,   5,   0],
        [  2,   3,   8,   1,   3],
        [  3,   3,   7,   0,   1]],

       [[  9,   9,   0,   4,   7],
        [  3,   2,   7,   2,   0],
        [  0,   4,   5,   5,   6],
        [  8,   4,   1,   4,   9]]])

In [246]:
cntArr = []
for i in np.arange(1,201):
    if  200 % i == 0:
        cntArr.append([i,200/i])      
len(cntArr)

12

## Reshaping

In [247]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [248]:
x = np.array([1, 2, 3])
x
y = x.reshape((1, 3))
y

array([1, 2, 3])

array([[1, 2, 3]])

In [249]:
x.ndim
x.shape
y.ndim
y.shape

1

(3,)

2

(1, 3)

In [250]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [251]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [252]:
y[np.newaxis, :]

array([[[1, 2, 3]]])

In [253]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

## Array Concatenation

In [254]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [255]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [256]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [257]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [258]:
np.concatenate([grid.flatten(),grid.flatten()]).reshape(2,6)

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [259]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [260]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [261]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [262]:
# 크기가 다르면 error 
np.vstack([y, grid])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 3

## Splitting of arrays


```ipython
np.split(arr, integer) # integer 등분
np.split(arr, 1-D array) # 구간 [n, m] : 0 ~ n-1, n ~ m - 1, m ~ len(arr)  ( index 기준 ) 
```

In [292]:
x = [1, 2, 3, 99, 99, 3, 2, 1,1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 ,x4 = np.split(x, [3,5,7])
print(x1, x2, x3,x4)

[1 2 3] [99 99] [3 2] [ 1  1  2  3 99 99  3  2  1]


In [265]:
np.split(x, [5, 1])

[array([ 1,  2,  3, 99, 99]),
 array([], dtype=int32),
 array([ 2,  3, 99, 99,  3,  2,  1])]

In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

In [ ]:
upper, lower = np.vsplit(grid, [2])
upper
lower

In [ ]:
left, right = np.hsplit(grid, [2])
left
right