In [9]:
# 넘파이 임포트
import numpy as np

In [10]:
l = [1,2,3,4]
# l+3 <- 불가능함!

In [11]:
# l을 np.array로 변환
# 형 변환을 한다면 , 행열연산을 할 수 있다.
arr1 = np.array(l)+3

AttributeError: module 'numpy' has no attribute 'array'

In [15]:
# reshape (n,m,...) 
# 배열의 모양을 변형시켜준다.
arr2 = np.array(l).reshape(4,1)

AttributeError: module 'numpy' has no attribute 'array'

In [12]:
arr3 = np.array([[3,4,5,6]])
arr1+arr3

AttributeError: module 'numpy' has no attribute 'array'

In [20]:
print("arr3.shape : ",arr3.shape)
print("arr3.ndim : " ,arr3.ndim)
# range와 유사함.
np.arange(10)


arr3.shape :  (1, 4)
arr3.ndim :  2


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
%%time
sum(np.arange(1,100000000))

Wall time: 17.3 s
<timed eval>:1: RuntimeWarning: overflow encountered in long_scalars


887459712

In [23]:
%%time
sum(range(1,100000000))

Wall time: 6.63 s


4999999950000000

In [26]:
# dtype = 자료형 을 이용하여 자료형을 명시해줄 수 있다.
# dtype을 사용하면 변수의 자료형을 볼 수 있다.
arr5 = np.array([1,2,3,4] , dtype = np.int8)
arr5_1 = np.array((1,2,3,4))

In [30]:
arr6 = np.ndarray((5,3,2))
print("arr6.dtype : ",arr6.dtype)
print("arr6.size : ",arr6.size)
print(arr6)


arr6.dtype :  float64
arr6.size :  30
[[[6.23042070e-307 4.67296746e-307]
  [1.69121096e-306 1.11260280e-306]
  [8.34441742e-308 1.37961302e-306]]

 [[9.34593493e-307 1.33511290e-306]
  [1.33511969e-306 1.69120416e-306]
  [1.37962117e-306 1.11260280e-306]]

 [[1.42420617e-306 1.60219035e-306]
  [1.00132398e-307 8.34425615e-308]
  [1.16820622e-307 1.27946076e-307]]

 [[2.22522597e-306 1.33511969e-306]
  [9.34604358e-307 1.11261027e-306]
  [2.22522597e-306 1.33511969e-306]]

 [[8.45594613e-307 1.86921958e-306]
  [6.89804133e-307 1.11261162e-306]
  [8.34443015e-308 2.22813476e-312]]]


In [43]:
arr7= np.arange(1,7).reshape(2,3)
print("arr7 \n",arr7)
# 행렬을 전치시켜줌 Transpose
print("arr7.T \n",arr7.T)
print("arr7.dot(arr.T)\n",arr7.dot(arr7.T))


arr7 
 [[1 2 3]
 [4 5 6]]
arr7.T 
 [[1 4]
 [2 5]
 [3 6]]
arr7.dot(arr.T)
 [[14 32]
 [32 77]]


In [47]:
# seed값에 따라 randint값이 달라진다.
np.random.seed(10)
# 60~100 사이의 값중 10개를 가져온다
np.random.randint(60,100,100)
#
np.random.choice(x,10)

array([87, 85, 96, 79, 94, 90, 94, 90, 77, 61])

In [48]:
x = np.random.randint(60,100,100)
s = 0
for i in x:
    if i % 3 ==0:
        s+=i
s

3240

In [61]:
x_t = []
for i in x:
    if i %3 ==0:
        x_t.append(i)
print("for문이용 : ",sum(x_t))
print("sum(x[x%3 ==0])",sum(x[x%3 ==0]))

for문이용 :  3240
sum(x[x%3 ==0]) 3240


In [57]:
y = np.array([3,4,6])
print("y : ", y)
# True,False를 이용하여 필요한 값만 가져올 수있다.
print("y[[True,False,True]] : ",y[[True,False,True]])


y :  [3 4 6]
y[[True,False,True]] :  [3 6]


In [76]:
np.random.seed(100)
x = np.random.randint(20,100,100000)
#3의배수이면서, 5의 배수인 것의 평균
ans = x[(x%3 ==0) & (x%5 == 0)].mean()
ans2 = np.sum(x[(x%3 ==0) & (x%5 == 0)])/x.size

print(ans)
print(ans2)

60.109298273404086
3.7947


In [80]:
# -1를 삽입하면, 장동으로 설치된다.
score = x.reshape(-1,4)
score.shape
score[[0,1]][:,[0,1]]

array([[28, 44],
       [68, 30]])

In [ ]:
# select avg(국어) + avg(영어)
# from  X
# where X >b

In [2]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

In [21]:
import tensorflow as tf
a=tf.constant(3)
sess = tf.Session()


ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'