## Fancy Indexing

In [6]:
import numpy as np
rand = np.random.RandomState(42)

x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [7]:
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

In [8]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [9]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col] # X[0, 2], X[1, 1], X[2, 3]
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
# broadcasting
X[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

## Combined Indexing

In [25]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [26]:
X[2, [2, 0, 1]]  # X[2,2], X[2,0], X[2,1]

array([10,  8,  9])

In [27]:
X[1:, [2, 0, 1]] # X[1,2], X[1,0], X[1,1], X[2,2], X[2,0], X[2,1], 

array([[ 6,  4,  5],
       [10,  8,  9]])

In [28]:
mask = np.array([1, 0, 1, 0], dtype=bool)
X[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

## Modifying Values with Fancy Indexing

In [30]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[0 1 2 3 4 5 6 7 8 9]
[ 0 99 99  3 99  5  6  7 99  9]


In [56]:
# x의 평균보다 큰값을 찾아 표준편차를 더하고고

np.random.seed(10)
x = np.random.randint(1,100,200)
print(x.std())
print(x.mean())
print(x)
# x = np.where( lambda x : x > x.mean(), x +x.std() , x)
# 아래와 같이 할려면, x를 float으로 형 변환해줘야한다.
# 이유 : ndarray는 같은 자료형만 있을 수 있다! std() == flaot!
x = x.astype('float')
x[x>x.mean()]+= x.std()
x



30.05877575684013
50.2
[10 16 65 29 90 94 30  9 74  1 41 37 17 12 55 89 63 34 73 79 50 52 55 78
 70 14 26 14 93 87 31 31 90 13 66 32 58 37 28 19 94 78 23 24 95 12 29 75
 89 10 16 19 81 72 89 12 18 47  8 76 29 34 85 97 89 45  6  5 72 89 89 51
 55 35 16 78 89 16  7 86 23 12 13 93 97 63 58 80 43 58 98 51 46 41 90 74
 38  1 19 24  4 30 17 85 83 15 52 80 18 51 54 26 49 18 33 82 81 42 91 13
 31 82 18 17  1 32 74 65 39 23 97 67 68 63 96 28 83 63 78 49 94 76 87 38
 12 22 34 96 44 89 97 74 41 44 91 72  9 86 73 29 31 90 26 79 82 86 63 14
 42 34  5 88 95 29 40 92 10  8 23 33  4 10 53 77 69 31 71 75 31 10  3 66
 14 76 53  6 94 85 49 63]


array([ 10.        ,  16.        ,  95.05877576,  29.        ,
       120.05877576, 124.05877576,  30.        ,   9.        ,
       104.05877576,   1.        ,  41.        ,  37.        ,
        17.        ,  12.        ,  85.05877576, 119.05877576,
        93.05877576,  34.        , 103.05877576, 109.05877576,
        50.        ,  82.05877576,  85.05877576, 108.05877576,
       100.05877576,  14.        ,  26.        ,  14.        ,
       123.05877576, 117.05877576,  31.        ,  31.        ,
       120.05877576,  13.        ,  96.05877576,  32.        ,
        88.05877576,  37.        ,  28.        ,  19.        ,
       124.05877576, 108.05877576,  23.        ,  24.        ,
       125.05877576,  12.        ,  29.        , 105.05877576,
       119.05877576,  10.        ,  16.        ,  19.        ,
       111.05877576, 102.05877576, 119.05877576,  12.        ,
        18.        ,  47.        ,   8.        , 106.05877576,
        29.        ,  34.        , 115.05877576, 127.05

In [57]:
x[i] -= 10
print(x)

[ 10.           6.          85.05877576  29.         110.05877576
 124.05877576  30.           9.          94.05877576   1.
  41.          37.          17.          12.          85.05877576
 119.05877576  93.05877576  34.         103.05877576 109.05877576
  50.          82.05877576  85.05877576 108.05877576 100.05877576
  14.          26.          14.         123.05877576 117.05877576
  31.          31.         120.05877576  13.          96.05877576
  32.          88.05877576  37.          28.          19.
 124.05877576 108.05877576  23.          24.         125.05877576
  12.          29.         105.05877576 119.05877576  10.
  16.          19.         111.05877576 102.05877576 119.05877576
  12.          18.          47.           8.         106.05877576
  29.          34.         115.05877576 127.05877576 119.05877576
  45.           6.           5.         102.05877576 119.05877576
 119.05877576  81.05877576  85.05877576  35.          16.
 108.05877576 119.05877576  16.           

In [64]:
x = np.zeros(10)
x[[0, 3]] = [4, 6]  # x[0] = 4, x[0] = 6, 두번 변경
print(x) 

[4. 0. 0. 6. 0. 0. 0. 0. 0. 0.]


In [65]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1  # x[3], x[4] 값 확인
x

array([4., 0., 1., 7., 1., 0., 0., 0., 0., 0.])

In [68]:
x = np.zeros(10)
np.add.at(x, i, 1) # x[3], x[4] 값 확인
print(x)

[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


## Sorting

In [69]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [70]:
x.sort()
print(x)

[1 2 3 4 5]


In [72]:
# index 반환
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [73]:
x[i]

array([1, 2, 3, 4, 5])

## Sorting along rows or columns

In [74]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [75]:
# sort each column of X
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [76]:
# sort each row of X
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## Partial Sorts: Partitioning

In [77]:
x = np.array([7, 0, 4, 1, -1, 5, 100])
np.partition(x, 3) # 3번쨰 요소 기준(x.sort()후 x[3])으로 작은 것은 왼쪽, 같거나 큰것은 오른쪽

array([  0,  -1,   1,   4,   5,   7, 100])

In [24]:
np.partition(x, 4)

array([  0,  -1,   1,   4,   5,   7, 100])

In [25]:
X

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [79]:
np.partition(X, 2, axis=1)


array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])

In [107]:
# 
np.random.seed(10)
x = np.random.randint(1,100,10)
print ( x)
print (np.sort(x))
print(np.partition(x,5))


[10 16 65 29 90 94 30  9 74  1]
[ 1  9 10 16 29 30 65 74 90 94]
[ 9  1 10 16 29 30 94 65 74 90]
