## - array의 값으로 1을 나누는 계산 

## loop를 사용한 계산

In [5]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

## UFuncs : *vectorized* operation

### 벡터 계산

In [6]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


### 1. 속도 비교

In [7]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)
%timeit (1.0 / big_array)

8.14 s ± 1.02 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.79 ms ± 1.09 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [10]:
# 2-D Array
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

### 2. 산술 연산

In [11]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) 
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [12]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [16]:
np.add(x, 2)

array([2, 3, 4, 5])

#### - wrapper

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|

### 3. Absolute value

In [17]:
# python 내장 함수
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [18]:
# numpy 함수
np.absolute(x) #  np.abs(x)

array([2, 1, 0, 1, 2])

In [19]:
np.random.randint(-100,100,100000)
%timeit abs(x)
%timeit np.abs(x)

1.96 µs ± 175 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
613 ns ± 10.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [23]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)


array([5., 5., 2., 1.])

### 4. 삼각 함수

In [24]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [25]:
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [26]:
# 역삼각 함수
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### 5. Exp, Log

In [28]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [29]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


## Advanced Ufunc Features

### 1. Specifying output

In [41]:
x = np.arange(5)
y = np.empty(5)
z = np.multiply(x, 10)
z

array([ 0, 10, 20, 30, 40])

In [43]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=z) # output 지정
z

array([ 0, 10, 20, 30, 40])

In [64]:
# 크기가 다름 
y = np.zeros(10)
np.power(2, x, out=y)
y

ValueError: operands could not be broadcast together with shapes () (5,) (10,) 

In [67]:
y = np.zeros(10)
print(y)
np.power(2, x, out=y[::2])  # y[::2] : step 2
y


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

### 2. Outer products

a = [a0, a1, ..., aM] , b = [b0, b1, ..., bN]

```
 [[a0*b0  a0*b1 ... a0*bN ]
 [a1*b0    .
 [ ...          .
 [aM*b0            aM*bN ]]
```


In [81]:
x = np.arange(1, 6)
np.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

## Aggregations

### 1. Sum

In [82]:
# python 내장함수
L = np.random.random(100)
sum(L)

51.42007124536917

In [83]:
# numpy 함수
np.sum(L) 

51.42007124536917

In [84]:
# 속도 비교
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

401 ms ± 104 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
4.06 ms ± 756 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### 2. Min, Max

In [88]:
min(big_array), max(big_array)

(1.9760029844606564e-06, 0.9999986906665383)

In [91]:
np.min(big_array), np.max(big_array)

(1.9760029844606564e-06, 0.9999986906665383)

In [92]:
big_array.min(), big_array.max(), big_array.sum()

(1.9760029844606564e-06, 0.9999986906665383, 500377.5463169642)

In [93]:
%timeit min(big_array)
%timeit np.min(big_array)
%timeit big_array.min()

74.4 ms ± 1.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
620 µs ± 28.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
607 µs ± 22.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### 3. Multi dimensional aggregates

In [94]:
M = np.random.random((3, 4))
M

array([[0.02444781, 0.79491573, 0.51605622, 0.68126578],
       [0.09626704, 0.24843591, 0.95486523, 0.0175746 ],
       [0.33121693, 0.04156122, 0.50477581, 0.38373791]])

In [95]:
M.sum()

4.595120190421901

In [96]:
# column 중에서 min
M.min(axis=0)

array([0.02444781, 0.04156122, 0.50477581, 0.0175746 ])

In [99]:
import numpy as np
?M.min
?np.power

Call signature:  np.power(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'power'>
File:            c:\users\painc\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
power(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

First array elements raised to powers from second array, element-wise.

Raise each base in `x1` to the positionally-corresponding power in
`x2`.  `x1` and `x2` must be broadcastable to the same shape. Note that an
integer type raised to a negative integer power will raise a ValueError.

Parameters
----------
x1 : array_like
    The bases.
x2 : array_like
    The exponents.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not prov

In [100]:
# row 중에서 min
M.min(axis=1)

array([0.02444781, 0.0175746 , 0.04156122])

### 4. Other aggregation functions

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |

### 5. reduce, accumulate

In [104]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [105]:
np.multiply.reduce(x)

120

In [110]:
#accumulate 을 사용하면 누적값을 알 수 있다.
# 누적 합
print(np.add.accumulate(x))
print(np.cumsum(x))

[ 1  3  6 10 15]
[ 1  3  6 10 15]


In [51]:
# 누적 곱
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

## Broadcasting

#### - 크기가 다른 array간의 연산

In [111]:
a = np.array([0, 1, 2])
a + 5

array([5, 6, 7])

In [113]:
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [114]:
b = np.array([5])
a + b

array([5, 6, 7])

In [115]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [116]:
M + a # shape 자동 변환

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [117]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [118]:
a + b


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [132]:
np.repeat(np.array([1,2]),30).size
np.tile(np.array([1,2]),4)

array([1, 2, 1, 2, 1, 2, 1, 2])

### 1. Concept

<img src='broadcasting.png'>broadcasting</img>

### 2. Rules

 1. 두 array의 차원 수가 다른 경우 더 적은 차원을 가진 배열의 모양이 앞쪽 (왼쪽)에 채워 짐
 2. 두 array의 모양이 어떤 차원에서도 일치하지 않으면 해당 차원에서 모양이 1 인 배열은 다른 모양과 일치하도록 늘어 남
 3. 어떤 차원에서든 크기가 일치하지 않고 1과 같지 않으면 오류가 발생

### 3. example 1

In [155]:
x = np.arange(99)
y = np.arange(1,4)
z = np.tile(y,33)
(x+z).reshape(33,3)

array([[  1,   3,   5],
       [  4,   6,   8],
       [  7,   9,  11],
       [ 10,  12,  14],
       [ 13,  15,  17],
       [ 16,  18,  20],
       [ 19,  21,  23],
       [ 22,  24,  26],
       [ 25,  27,  29],
       [ 28,  30,  32],
       [ 31,  33,  35],
       [ 34,  36,  38],
       [ 37,  39,  41],
       [ 40,  42,  44],
       [ 43,  45,  47],
       [ 46,  48,  50],
       [ 49,  51,  53],
       [ 52,  54,  56],
       [ 55,  57,  59],
       [ 58,  60,  62],
       [ 61,  63,  65],
       [ 64,  66,  68],
       [ 67,  69,  71],
       [ 70,  72,  74],
       [ 73,  75,  77],
       [ 76,  78,  80],
       [ 79,  81,  83],
       [ 82,  84,  86],
       [ 85,  87,  89],
       [ 88,  90,  92],
       [ 91,  93,  95],
       [ 94,  96,  98],
       [ 97,  99, 101]])

In [156]:
M = np.ones((2, 3))
a = np.arange(3)
print(M.shape)
print(a.shape)

(2, 3)
(3,)


In [159]:
print(M)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


- ``M.shape = (2, 3)``
- ``a.shape = (3,)``

rule 1 >>>

- ``M.shape -> (2, 3)``
- ``a.shape -> (1, 3)``

rule 2 >>> 

- ``M.shape -> (2, 3)``
- ``a.shape -> (2, 3)``

broadcasting **a** :  ``(2, 3)``:

`` [[0, 1, 2]
  [0, 1, 2]]``

In [160]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

### 4. example 2

In [145]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
print(a)
print(b)

[[0]
 [1]
 [2]]
[0 1 2]


- ``a.shape = (3, 1)``
- ``b.shape = (3,)``

Rule 1 >>>

- ``a.shape -> (3, 1)``
- ``b.shape -> (1, 3)``

rule 2 >>>

- ``a.shape -> (3, 3)``
- ``b.shape -> (3, 3)``

broadcasting **a** :

``[[0, 0, 0]
 [1, 1, 1]
 [2, 2, 2]]``

broadcasting **b** :

``[[0, 1, 2]
 [0, 1, 2]
 [0, 1, 2]]``

In [146]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### 5. example 3

In [162]:
M = np.ones((3, 2))
a = np.arange(3)
print(M)
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2]


- ``M.shape = (3, 2)``
- ``a.shape = (3,)``

rule 1 >>>

- ``M.shape -> (3, 2)``
- ``a.shape -> (1, 3)``

rule 2 >>>

- ``M.shape -> (3, 2)``
- ``a.shape -> (3, 3)``

rule 3 >>> error

In [164]:
M + a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 