## Comparison

### 1. operator

In [36]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])

In [37]:
x < 3  # less than

array([ True,  True, False, False, False])

In [38]:
x > 3  # greater than

array([False, False, False,  True,  True])

In [39]:
x <= 3  # less than or equal

array([ True,  True,  True, False, False])

In [40]:
x >= 3  # greater than or equal

array([False, False,  True,  True,  True])

In [41]:
x != 3  # not equal

array([ True,  True, False,  True,  True])

In [42]:
x == 3  # equal

array([False, False,  True, False, False])

It is also possible to do an element-wise comparison of two arrays, and to include compound expressions:

In [43]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

#### - N-D array

In [44]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [45]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

### 2. ufunc

| Operator	    | Equivalent ufunc    | Operator	   | Equivalent ufunc    |
|---------------|---------------------|---------------|---------------------|
|``==``         |``np.equal``         |``!=``         |``np.not_equal``     |
|``<``          |``np.less``          |``<=``         |``np.less_equal``    |
|``>``          |``np.greater``       |``>=``         |``np.greater_equal`` |

### 3. Boolean Arrays 사용

In [46]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


#### - Counting entries

In [47]:
# 6보다 작은 요소 개수
np.count_nonzero(x < 6)

8

In [48]:
# 6보다 작은 요소 개수, False : 0, True : 1
np.sum(x < 6)

8

In [49]:
# 각 row에서 6보다 작은 요소 개수
np.sum(x < 6, axis=1)

array([4, 2, 2])

In [50]:
# 8보다 큰 요소가 있는지?
np.any(x > 8)

True

In [51]:
# 0 보다 작은 요소가 있는지?
np.any(x < 0)

False

In [52]:
# 모든 요소가 10보다 작은지?
np.all(x < 10)

True

In [53]:
# 모든 요소가 6인지?
np.all(x == 6)

False

In [54]:
# 각 row의 요소가 모두 8보다 작은지?
np.all(x < 8, axis=1)

array([ True, False,  True])

### 4. Boolean operators

In [55]:
x = np.random.normal(0, 1, 1000)
np.sum((x > 0.5) & (x < 0.7))

60

In [56]:
np.sum(~( (x <= 0.5) | (x >= 0.7) ))

60

#### - operator

| Operator	    | Equivalent ufunc    || Operator	    | Equivalent ufunc    |
|---------------|---------------------|---------------|---------------------|
|``&``          |``np.bitwise_and``   ||&#124;         |``np.bitwise_or``    |
|``^``          |``np.bitwise_xor``   ||``~``          |``np.bitwise_not``   |

In [57]:
x < 0.5

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True, False, False, False,  True,  True,
        True,  True, False, False,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True, False, False,  True,  True,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [58]:
# 조건 선택
x[x < 0.5].shape

(684,)

In [59]:
condition = (x < 0.5)
print(np.median(x[condition]))
print(np.max(x[condition]))
print(np.min(x[condition]))
print(np.median(x[~condition]))
print(np.max(x[~condition]))
print(np.min(x[~condition]))

-0.4188621076650868
0.48993978101982544
-2.9165716120394944
1.0565940849094382
3.2994801714372137
0.5016171403570214


In [61]:
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
print(A)
print(B)
print(A | B)

[ True False  True False  True False]
[ True  True  True False  True  True]
[ True  True  True False  True  True]


In [62]:
# error
A or B

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [29]:
x = np.arange(10)
(x > 4) & (x < 8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])

In [30]:
# error
(x > 4) and (x < 8)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()