In [3]:
import numpy as np
## 1000000 개의 데이터를 만들어서
np.random.seed(100)
x = np.random.randint(60,100,1000000)
x = x.reshape(-1,4)



In [4]:
print(x[:,3]>np.mean(x[:3]) ,0)
print(x[x[:,3]>np.mean(x[:3])] ,0)
print(x[x[:,3]>np.mean(x[:3] ),1] )

np.mean(x[x[:,3]>np.mean(x[:3]),0:2],axis=1)

[ True  True False ... False False  True] 0
[[68 84 63 99]
 [83 75 70 90]
 [94 84 75 96]
 ...
 [90 81 77 82]
 [64 89 81 87]
 [81 84 90 99]] 0
[84 75 84 ... 81 89 84]


array([76. , 79. , 89. , ..., 85.5, 76.5, 82.5])

In [1]:
arr = np.array([1,2,3,4,5,6])
print(arr)

# 아래 두개는 같은 기능을 하지만, 조금 다르다
print("sum = ",np.sum(arr))
print("sum = ",arr.sum())

dir(np.ndarray)

NameError: name 'np' is not defined

In [13]:
# 1,2,3의 원소를 갖는 1차원 배열 Array생성
a = np.array([1,2,3])
# 차원 확인
print("차원 보기 : " ,a.ndim)
print("배열의 상세 크기 확인 : ",a.shape)
print("데이터 타입 : ",a.dtype)
print("형변환 : ",a.astype(object) , a.astype(object).dtype )
# nan이 들어있으면, 계산이 안된다.
print("nan이 들어있으면, 계산이 안된다. " , np.array([1,2,3,np.nan]).sum())
# nansum이라는 함수를 사용하면 nan값을 제외하고 사용할 수 있다.
print("nan값을 제외하고 계산" , np.nansum(np.array([1,2,3,np.nan])))



차원 보기 :  1
배열의 상세 크기 확인 :  (3,)
데이터 타입 :  int32
형변환 :  [1 2 3] object
nan이 들어있으면, 계산이 안된다.  nan
nan값을 제외하고 계산 6.0


In [29]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
x_2 = x.reshape(2,5)
print(x_2)
print(x_2.flatten()) # 1차원으로 변경
x_2_t = x_2.T # 전치해주기
print("--전치후--")
print(x_2_t)
print(x_2_t.ravel()) # 1차원으로 변경

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
--전치후--
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[0 5 1 6 2 7 3 8 4 9]


In [49]:
## linspace를 사용하여 0~60까지의 10개의 구간을 배열로 생성
np.linspace(0,60,10)

np.random.seed(10)
print("randint\n",np.random.randint(1,10,20))
print("rand \n",np.random.rand(3,3,2))
obj = [1,2,3,4]
# 내부값 랜덤하게 바꿔주기
np.random.shuffle(obj)
obj

randint
 [5 1 2 1 2 9 1 9 7 5 4 1 5 7 9 2 9 5 2 4]
rand 
 [[[0.54088093 0.13145815]
  [0.41366737 0.77872881]
  [0.58390137 0.18263144]]

 [[0.82608225 0.10540183]
  [0.28357668 0.06556327]
  [0.05644419 0.76545582]]

 [[0.01178803 0.61194334]
  [0.33188226 0.55964837]
  [0.33549965 0.41118255]]]


[2, 1, 4, 3]

In [61]:
arr = np.ndarray((3,3))
print("arr\n",arr)
print("arr[[0,2]]\n",arr[[0,2]])
print("arr[:,[2,1]]\n",arr[:,[2,1]])
print("arr[[0,2]][:,[2,1]]\n",arr[[0,2]][:,[2,1]])

arr
 [[ 6.66666667 13.33333333 20.        ]
 [26.66666667 33.33333333 40.        ]
 [46.66666667 53.33333333 60.        ]]
arr[[0,2]]
 [[ 6.66666667 13.33333333 20.        ]
 [46.66666667 53.33333333 60.        ]]
arr[:,[2,1]]
 [[20.         13.33333333]
 [40.         33.33333333]
 [60.         53.33333333]]
arr[[0,2]][:,[2,1]]
 [[20.         13.33333333]
 [60.         53.33333333]]


In [63]:
np.random.seed(100)
# 1~99사이의 숫자를 10개 뽑는다.
arr = np.random.randint(1,99,10)
# 배열 안에있는 값중 50초과인 것을 반환.(조건문)
arr[arr>50]

array([68, 88, 80, 95, 53, 54])

In [92]:
np.random.seed(100)
# 1~100의 숫자 50개를 10x5의 행렬로 만들어줌 reshape(행,열)
arr=np.random.randint(1,100,50).reshape(10,5)
print(arr)

row_sum = []
for i in np.arange(arr.shape[0]):
    row_sum.append(np.sum(arr[i]))
print("for이용 : ",row_sum)

#axis이용하기
#axis = 1 -> 열기준 연산
print("axis = 1 -> ",arr.sum(axis = 1))
col_sum = []
for i in np.arange(arr.shape[1]):
    col_sum.append(np.sum(arr[:,i]))
print("for이용 : ",col_sum)
#axis = 0 -> 행기준 연산
print("axis = 0 -> ",arr.sum(axis = 0))



[[ 9 25 68 88 80]
 [49 11 95 53 99]
 [54 67 99 15 35]
 [25 16 61 59 17]
 [10 94 87  3 28]
 [ 5 32  2 14 84]
 [ 5 92 60 68  8]
 [50 48 66 62 15]
 [56 72 81  3 95]
 [20 99 64 54 28]]
for이용 :  [270, 307, 270, 178, 222, 137, 233, 241, 307, 265]
axis = 1 ->  [270 307 270 178 222 137 233 241 307 265]
for이용 :  [283, 556, 683, 419, 489]
axis = 0 ->  [283 556 683 419 489]


In [100]:
a = np.random.randint(1,100,10)
b = np.random.randint(1,100,10)

#거듭제곱
print(np.square(a))
#wprhqrms
print(np.sqrt(a))
# a,b의 거리
print(np.hypot(a,b))
print(np.rint(x))




[ 324 8281 8836 9409 5625 2916  961 4624  841 1444]
[4.24264069 9.53939201 9.69535971 9.8488578  8.66025404 7.34846923
 5.56776436 8.24621125 5.38516481 6.164414  ]
[ 84.92938243  92.76313923  94.64142856  98.00510191 111.12605455
  59.93329626  73.8241153   69.85699679  31.38470965  54.45181356]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [123]:
# np.where(condition,ture_value,false_value)
# np.where(조건 , 참일시 return, 거짓일시 return)
x = np.random.randint(60,100,100000)
# 평균보다 클 경우 'P'
# 평균보다 작을 경우 'F'

judge = []
#for문 사용
#오래걸린다..
for i in x:
    if i >= x.mean():
        judge.append('Pass')
    else:
        judge.append("Fail")
# print(judge.head())
#where메소드 사용
np.where(x>=x.mean(),'Pass','Fail')

In [170]:
%%time
x = np.random.randint(60,100,100000)
# 평균보다 클 경우 'P'
# 평균보다 작을 경우 'F'

judge = []
#for문 사용
#오래걸린다..
for i in x:
    if i >= x.mean():
        judge.append('Pass')
    else:
        judge.append("Fail")


Wall time: 20.5 s


In [171]:
%%time
x = np.random.randint(60,100,100000)
# 평균보다 클 경우 'P'
# 평균보다 작을 경우 'F'
#where메소드 사용
np.where(x>=x.mean(),'Pass','Fail')

Wall time: 12 ms


array(['Pass', 'Fail', 'Fail', ..., 'Fail', 'Pass', 'Pass'], dtype='<U4')

In [124]:
# 90 이상 : A
# 80 이상 : B
# 70 이상 : C
judge1 = np.where(x>=90,'A',np.where(x>=80,'B','C'))
judge1

array(['A', 'A', 'C', ..., 'A', 'B', 'C'], dtype='<U1')

In [129]:
obj = np.random.choice(['banana','apple','grape'],100)
le1 = np.where(obj == np.unique(obj)[0],0,
            np.where(obj == np.unique(obj)[1],1,2))
le1

array([2, 2, 1, 1, 0, 2, 0, 1, 0, 2, 1, 0, 1, 2, 2, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 2, 0, 0, 2, 2, 0, 2, 2, 1, 1, 2, 0, 0, 1, 1, 1, 2, 0,
       2, 0, 1, 0, 1, 1, 0, 2, 2, 1, 1, 0, 2, 2, 2, 0, 1, 2, 0, 0, 1, 0,
       2, 0, 1, 1, 2, 1, 0, 2, 0, 2, 0, 1, 0, 1, 0, 2, 1, 2, 0, 1, 0, 0,
       1, 0, 0, 2, 0, 1, 2, 2, 1, 2, 0, 1])

In [140]:
t = np.zeros((100,3))
t[0,:]
for i in np.arange(100):
    t[i,le1[i]]=i
t

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  2.,  0.],
       [ 0.,  3.,  0.],
       [ 4.,  0.,  0.],
       [ 0.,  0.,  5.],
       [ 6.,  0.,  0.],
       [ 0.,  7.,  0.],
       [ 8.,  0.,  0.],
       [ 0.,  0.,  9.],
       [ 0., 10.,  0.],
       [11.,  0.,  0.],
       [ 0., 12.,  0.],
       [ 0.,  0., 13.],
       [ 0.,  0., 14.],
       [ 0., 15.,  0.],
       [16.,  0.,  0.],
       [17.,  0.,  0.],
       [18.,  0.,  0.],
       [19.,  0.,  0.],
       [20.,  0.,  0.],
       [ 0., 21.,  0.],
       [ 0., 22.,  0.],
       [ 0., 23.,  0.],
       [24.,  0.,  0.],
       [25.,  0.,  0.],
       [ 0.,  0., 26.],
       [27.,  0.,  0.],
       [28.,  0.,  0.],
       [ 0.,  0., 29.],
       [ 0.,  0., 30.],
       [31.,  0.,  0.],
       [ 0.,  0., 32.],
       [ 0.,  0., 33.],
       [ 0., 34.,  0.],
       [ 0., 35.,  0.],
       [ 0.,  0., 36.],
       [37.,  0.,  0.],
       [38.,  0.,  0.],
       [ 0., 39.,  0.],
       [ 0., 40.,  0.],
       [ 0., 41.

In [146]:
#concatenate : 배열 합치기
print(np.concatenate([t,le1.reshape(-1,1)],axis=1))


[[ 0.  0.  0.  2.]
 [ 0.  0.  1.  2.]
 [ 0.  2.  0.  1.]
 [ 0.  3.  0.  1.]
 [ 4.  0.  0.  0.]
 [ 0.  0.  5.  2.]
 [ 6.  0.  0.  0.]
 [ 0.  7.  0.  1.]
 [ 8.  0.  0.  0.]
 [ 0.  0.  9.  2.]
 [ 0. 10.  0.  1.]
 [11.  0.  0.  0.]
 [ 0. 12.  0.  1.]
 [ 0.  0. 13.  2.]
 [ 0.  0. 14.  2.]
 [ 0. 15.  0.  1.]
 [16.  0.  0.  0.]
 [17.  0.  0.  0.]
 [18.  0.  0.  0.]
 [19.  0.  0.  0.]
 [20.  0.  0.  0.]
 [ 0. 21.  0.  1.]
 [ 0. 22.  0.  1.]
 [ 0. 23.  0.  1.]
 [24.  0.  0.  0.]
 [25.  0.  0.  0.]
 [ 0.  0. 26.  2.]
 [27.  0.  0.  0.]
 [28.  0.  0.  0.]
 [ 0.  0. 29.  2.]
 [ 0.  0. 30.  2.]
 [31.  0.  0.  0.]
 [ 0.  0. 32.  2.]
 [ 0.  0. 33.  2.]
 [ 0. 34.  0.  1.]
 [ 0. 35.  0.  1.]
 [ 0.  0. 36.  2.]
 [37.  0.  0.  0.]
 [38.  0.  0.  0.]
 [ 0. 39.  0.  1.]
 [ 0. 40.  0.  1.]
 [ 0. 41.  0.  1.]
 [ 0.  0. 42.  2.]
 [43.  0.  0.  0.]
 [ 0.  0. 44.  2.]
 [45.  0.  0.  0.]
 [ 0. 46.  0.  1.]
 [47.  0.  0.  0.]
 [ 0. 48.  0.  1.]
 [ 0. 49.  0.  1.]
 [50.  0.  0.  0.]
 [ 0.  0. 51.  2.]
 [ 0.  0. 52

In [151]:
np.concatenate([t,le1.reshape(-1,1)],axis=1)



array([[ 0.,  0.,  0.,  2.],
       [ 0.,  0.,  1.,  2.],
       [ 0.,  2.,  0.,  1.],
       [ 0.,  3.,  0.,  1.],
       [ 4.,  0.,  0.,  0.],
       [ 0.,  0.,  5.,  2.],
       [ 6.,  0.,  0.,  0.],
       [ 0.,  7.,  0.,  1.],
       [ 8.,  0.,  0.,  0.],
       [ 0.,  0.,  9.,  2.],
       [ 0., 10.,  0.,  1.],
       [11.,  0.,  0.,  0.],
       [ 0., 12.,  0.,  1.],
       [ 0.,  0., 13.,  2.],
       [ 0.,  0., 14.,  2.],
       [ 0., 15.,  0.,  1.],
       [16.,  0.,  0.,  0.],
       [17.,  0.,  0.,  0.],
       [18.,  0.,  0.,  0.],
       [19.,  0.,  0.,  0.],
       [20.,  0.,  0.,  0.],
       [ 0., 21.,  0.,  1.],
       [ 0., 22.,  0.,  1.],
       [ 0., 23.,  0.,  1.],
       [24.,  0.,  0.,  0.],
       [25.,  0.,  0.,  0.],
       [ 0.,  0., 26.,  2.],
       [27.,  0.,  0.,  0.],
       [28.,  0.,  0.,  0.],
       [ 0.,  0., 29.,  2.],
       [ 0.,  0., 30.,  2.],
       [31.,  0.,  0.,  0.],
       [ 0.,  0., 32.,  2.],
       [ 0.,  0., 33.,  2.],
       [ 0., 3

In [166]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8],[9,10]])
print ("a\n",a)
print ("\nb\n",b)
print("\nconcat (a , b) axis = 0\n",np.concatenate((a,b),axis=0))
print("\nb.T \n",b.T)
print("\nconcat (a , b.T) axis = 1\n",np.concatenate((a,b.T),axis=1))
print("\nconcat (a , b) axis = none\n",np.concatenate((a, b), axis=None))


a
 [[1 2]
 [3 4]]

b
 [[ 5  6]
 [ 7  8]
 [ 9 10]]

concat (a , b) axis = 0
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

b.T 
 [[ 5  7  9]
 [ 6  8 10]]

concat (a , b.T) axis = 1
 [[ 1  2  5  7  9]
 [ 3  4  6  8 10]]

concat (a , b) axis = none
 [ 1  2  3  4  5  6  7  8  9 10]


In [177]:
x = np.arange(1,10,3)
x_prob = np.exp(x)
print(x)
print(x_prob)


[1 4 7]
[   2.71828183   54.59815003 1096.63315843]


In [285]:
%%time
# 문제
# 1. 값들을 확율로 변경시키기
# 2. 확율값이 높은값의 위치에따라 apple banana grape로 치환
# 3. 각각 갯수 세기

np.random.seed(100)
items = ['apple', 'banana', 'grape']
x = np.random.randint(1,10,30000000).reshape(-1,3)
# np.unique(np.argmax(np.exp(x)/np.sum(np.exp(x),axis=1).reshape(-1,1),axis=1), return_counts = True)[1]

dict(zip(items, np.unique(
        np.argmax(np.exp(x)/np.sum(np.exp(x),axis=1).reshape(-1,1),axis=1),
            return_counts = True)[1]))


Wall time: 1.79 s


{'apple': 3906537, 'banana': 3293909, 'grape': 2799554}

In [288]:
import numpy as np
import pandas as pd


In [302]:
# s = pd.Series([1,2,3])
s = pd.Series([1,2,3],index =[3,2,1])
# 느낌상 key : value 느낌으로 구현하는 것 같다
s[1]


3